[FIX]  исправил замечания
dessanhemrayev/cx_test_base_two_dessan pull request #1
Opened 2022-10-04 21:15 UTC by dessanhemrayev

2022-10-10 16:49 UTC, isserver1 requested changes

2022-10-10 16:49 UTC, isserver1 commented on models/sale_order.py
> +                item.order_id._reset_sequence()
Допустим у нас есть 5 строк.
Строки 1, 4 и5  принадлежат Sales Order A
Строка 2 и 3  принадлежат   Sales Order B

 В итоге у нас будет 3 вызова для первого заказа и 2 для второго. Хотя достаточно одного вызова для каждого из них.

2022-10-10 16:49 UTC, isserver1 commented on models/sale_order.py
> +            item._reset_sequence()
Допустим, у нас есть заказ Sales Order A в котором есть 10 строк.
Пользователь удаляет заказ целиком. Что произойдет в данном случае?

2022-10-10 16:56 UTC, isserver1 requested changes
Для понимания работы тестов лучше глянуть существующие модули. Лучше всего ОСА
Например [вот](https://github.com/OCA/stock-logistics-warehouse/blob/f58a86898fe989da761cc64c0d0ff5c50652c98a/procurement_auto_create_group/tests/test_auto_create.py#L184)

2022-10-10 16:56 UTC, isserver1 commented on tests/test_sale_order_line_sequence.py
> +        self.check_assertEqual(line_1)
а почему именно  check_assertEqual?
Нам нужно проветрить соответствие результата ожидаемому нами эталонному значению.
Например, номер строки 1 должен быть равен "1".
Для этого используется конструкция вида 
`self.assertEqual(order.order_line[0].line_number, 1, msg="Line number must be equal to 1")
`

2022-10-11 04:17 UTC, dessanhemrayev commented on tests/test_sale_order_line_sequence.py
> +        self.check_assertEqual(line_1)
я написал отдельный метод(check_assertEqual) для этого, объясню почему
во всех методах используется вот это выражение self.assertEqual(order.order_line[0].line_number, 1, msg="Line number must be equal to 1")
и если в заказе 10 позиций то для проверки каждого теста пришлось бы написать 10 строк таких выражений  (да я понимаю это может быть избыточно) но все таки сэкономленные +-40 строк кода стоить того

2023-02-12 12:45 UTC, closed without merging